### ISSUE TITLE
Posts table isn't included in migrations

### ISSUE THREAD

**Issue by tylerpixelguild** [Trexology/laravel-reviewRateable#9]
I get this error:
"SQLSTATE[42S02]: Base table or view not found: 1146 Table 'database.posts' doesn't exist (SQL: select * from `posts` limit 1)"

And I looked in the migrations and there aren't any for the posts table.

**Comment by Trexology** [comment]
Hi,

$post is just an example given. 

please use your own entity for the review. Thanks
